/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcdemo;


import java.sql.*;

/**
 *
 * @author atmoore3
 */

@SuppressWarnings("serial")
public class Patient extends javax.swing.JFrame {

    
    
    
	@SuppressWarnings("unused")
	private String ConnectionUrl = "";
	private Driver login_Driver;
	private static Connection myConn;
    /**
     * Creates new form Patient
     */
   
    public Patient(Driver driver) {
       	setLogin_Driver(driver);
        getLogin_Driver();
		setMyConn(Driver.getMyConn());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Patient_Label = new javax.swing.JLabel();
        Log_Out_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        billingList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Login");

        Patient_Label.setBackground(java.awt.Color.red);
        Patient_Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Patient_Label.setText("Welcome Patient");

        Log_Out_Button.setText("Log Out");
        Log_Out_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Log_Out_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        Log_Out_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_Out_ButtonActionPerformed(evt);
            }
        });

        billingList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = getLogin_Driver().search_patient();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(billingList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Log_Out_Button)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Patient_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Patient_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Log_Out_Button))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Log_Out_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_Out_ButtonActionPerformed
        // TODO add your handling code here:
    	try {
			getLogin_Driver();
			Driver.myConn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        System.exit(0);
    }//GEN-LAST:event_Log_Out_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    Driver getLogin_Driver() {
		return login_Driver;
	}

	void setLogin_Driver(Driver login_Driver) {
		this.login_Driver = login_Driver;
	}

	static Connection getMyConn() {
		return myConn;
	}

	static void setMyConn(Connection myConn) {
		Patient.myConn = myConn;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log_Out_Button;
    private javax.swing.JLabel Patient_Label;
    private javax.swing.JList<String> billingList;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
